Traceback (most recent call last):
  File "/home/dieaigar/Work/BOAND/planner/planner.py", line 647, in <module>
    main(sys.argv, len(sys.argv))
  File "/home/dieaigar/Work/BOAND/planner/planner.py", line 622, in main
    solution = boand_star(domain_file, problem_file, solution_folder, use_metric=metric, use_cp_heuristic=heuristic, use_best_case_heuristic=best_heuristic, use_worst_case_heuristic=worst_heuristic, use_size_heuristic=size_heuristic, use_selector=selector)
  File "/home/dieaigar/Work/BOAND/planner/planner.py", line 527, in boand_star
    new_policy = extend_policy(current_policy, state, nondet_action, nondet_to_det_action[nondet_action], nondet_action_to_successors[nondet_action], task)
  File "/home/dieaigar/Work/BOAND/planner/planner.py", line 274, in extend_policy
    update_g_values(new_policy,state,successors, task)
  File "/home/dieaigar/Work/BOAND/planner/planner.py", line 205, in update_g_values
    update_g_brute(policy, task)
  File "/home/dieaigar/Work/BOAND/planner/planner.py", line 220, in update_g_brute
    reached_states = {det_action.apply(state) for det_action in action[1]}
  File "/home/dieaigar/Work/BOAND/planner/planner.py", line 220, in <setcomp>
    reached_states = {det_action.apply(state) for det_action in action[1]}
  File "/home/dieaigar/Work/BOAND/planner/pyperplan/pyperplan/task.py", line 63, in apply
    return (state - self.del_effects) | self.add_effects
MemoryError
real 71.64
user 72.74
sys 1.96
